meta:
  # engine: 4.1.0
  version: 0.1
  author: tsiooh

units:
  # Proxy Spacing Variables
  kx: u # cherry mx
  ky: u # cherry mx
  # Padding Variables
  px: kx + 2
  py: ky + 2
  #$default_width: u
  #$default_height: u

points:
  mirror: &mirror
    ref: matrix_inner_bottom
    distance: 1kx
  zones:
    matrix: # nazwa strefy
      columns:
        outer:
        pinky:
        ring:
        middle:
        index:
        inner:
      rows:
        bottom:
        middle:
        top:
    spacerow:
      anchor:
        ref: matrix_outer_bottom
        shift: [0,-1ky]
      columns:
        outer:
        pinky:
        ring:
        middle:
        index:
        space:
          key:
            width: 2kx
            shift: [0.5kx,0]
            asym: left

outlines:
  raw:
    - what: rectangle
      where: 
        #ref: matrix_outer_bottom
        ref: spacerow_outer
      size: [12u, 4u]
      adjust:
        shift: [5.5u, 1.5u]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  print:
    - name: raw
    - name: keys
      operation: stack


