meta:
  # engine: 4.1.0
  version: 0.1
  author: tsiooh

units:
  # Proxy Spacing Variables
  kx: U # cherry mx
  ky: U # cherry mx
  # Padding Variables
  px: kx+2
  py: ky+2
  $default_width: U
  $default_height: U

points:
  key:
    padding: px
    spread: py
  mirror:
    ref: matrix_inner_spacerow
  zones:
    matrix:
      #anchor:
        #shift: [50, -100]
      columns:
        outer:
        pinky:
        ring:
        middle:
        index:
        inner:
          rows:
            spacerow:
              width: kx+px
              shift: [px/2,0]
              asym: left
            bottom:
              shift: [-px/2, 0]
      rows:
        spacerow:
        bottom:
        middle:
        top:
outlines:
  raw:
    - what: rectangle
      where: 
        ref: matrix_outer_spacerow
      size: [12px, 4px]
      adjust:
        shift: [5.5px, 1.5px]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  print:
    - name: raw
    - name: keys
      operation: stack
